apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: prod
  labels:
    app: aws-eks-terraform-cicd-pipeline-backend
spec:
  selector:
    app: aws-eks-terraform-cicd-pipeline-backend
  ports:
    - protocol: TCP
      port: 80               # Service port
      targetPort: 80         # Should match containerPort in your backend deployment.yaml
  type: LoadBalancer
