apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: aws-eks-terraform-cicd-pipeline-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-eks-terraform-cicd-pipeline-backend
  template:
    metadata:
      labels:
        app: aws-eks-terraform-cicd-pipeline-backend
    spec:
      containers:
      # Backend container
      - name: backend
        image: 575791034546.dkr.ecr.ap-south-1.amazonaws.com/backend_repo:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 750Mi
      {% comment %} # NGINX container
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 443
        volumeMounts:
        - name: ssl-certs
          mountPath: /etc/nginx/ssl
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: ssl-certs
        secret:
          secretName: nginx-ssl
      - name: nginx-config
        configMap:
          name: nginx-config {% endcomment %}
